### ISSUE TITLE
Hata Veriyor !

### ISSUE THREAD

**Issue by mertnrist** [Serhann/discord-turkce-muzik-bot#5]
PS C:\Users\b2ner\Desktop\discord-turkce-muzik-bot-master\~> node bot.js
F-AT()#4718 (473255019534090250) ismi ile giriş yapıldı.
(node:2360) UnhandledPromiseRejectionWarning: Error: FFMPEG not found
    at Function.selectFfmpegCommand (C:\Users\b2ner\Desktop\discord-turkce-muzik-bot-master\~\node_modules\prism-media\src\transcoders\ffmpeg\Ffmpeg.js:46:13)
    at new FfmpegTranscoder (C:\Users\b2ner\Desktop\discord-turkce-muzik-bot-master\~\node_modules\prism-media\src\transcoders\ffmpeg\Ffmpeg.js:7:37)
    at new MediaTranscoder (C:\Users\b2ner\Desktop\discord-turkce-muzik-bot-master\~\node_modules\prism-media\src\transcoders\MediaTranscoder.js:10:19)
    at new Prism (C:\Users\b2ner\Desktop\discord-turkce-muzik-bot-master\~\node_modules\prism-media\src\Prism.js:5:23)
    at new VoiceConnection (C:\Users\b2ner\Desktop\discord-turkce-muzik-bot-master\~\node_modules\discord.js\src\client\voice\VoiceConnection.js:46:18)
    at Promise (C:\Users\b2ner\Desktop\discord-turkce-muzik-bot-master\~\node_modules\discord.js\src\client\voice\ClientVoiceManager.js:63:22)
    at new Promise (<anonymous>)
    at ClientVoiceManager.joinChannel (C:\Users\b2ner\Desktop\discord-turkce-muzik-bot-master\~\node_modules\discord.js\src\client\voice\ClientVoiceManager.js:45:12)
    at VoiceChannel.join (C:\Users\b2ner\Desktop\discord-turkce-muzik-bot-master\~\node_modules\discord.js\src\structures\VoiceChannel.js:130:30)
    at Client.client.on.m (C:\Users\b2ner\Desktop\discord-turkce-muzik-bot-master\~\bot.js:14:15)
(node:2360) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2360) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Nasıl  FFMPEG indircez !!!!!!!111

**Comment by Dogacanacc** [comment]
npm i ffmpeg Bu Şekilde Fakat bende indirdim çalışmadı hayla aynı yatayı veriyor

**Comment by Serhann** [comment]
@Fessqer @Dogacanacc 

Güncelleme yaptım, yeni versiyon şu anda problemsiz çalışmakta.
